OBJS_8_2_1 = problem.8.2.1.o
OBJS_8_2_2 = problem.8.2.2.o
OBJS_8_2_3 = problem.8.2.3.o
OBJS_8_2_4 = problem.8.2.4.o
OBJS_8_2_5 = problem.8.2.5.o
OBJS_8_2_6 = problem.8.2.6.o
OBJS_8_2_7 = problem.8.2.7.o
OBJS_8_2_8 = problem.8.2.8.o
OBJS_8_2_9 = problem.8.2.9.o
OBJS_8_2_10 = problem.8.2.10.o
OBJS_8_2_11 = problem.8.2.11.o
CC = g++
CFLAGS = -c -Wall -std=c++11
LFLAGS = -Wall

all : test_8_2_1 test_8_2_2 test_8_2_3 test_8_2_4 test_8_2_5 test_8_2_6 test_8_2_7 test_8_2_8 test_8_2_9 test_8_2_10 test_8_2_11

test_8_2_1 : $(OBJS_8_2_1)
	$(CC) $(LFLAGS) $(OBJS_8_2_1) -o test_8_2_1

test_8_2_2 : $(OBJS_8_2_2)
	$(CC) $(LFLAGS) $(OBJS_8_2_2) -o test_8_2_2

test_8_2_3 : $(OBJS_8_2_3)
	$(CC) $(LFLAGS) $(OBJS_8_2_3) -o test_8_2_3

test_8_2_4 : $(OBJS_8_2_4)
	$(CC) $(LFLAGS) $(OBJS_8_2_4) -o test_8_2_4

test_8_2_5 : $(OBJS_8_2_5)
	$(CC) $(LFLAGS) $(OBJS_8_2_5) -o test_8_2_5

test_8_2_6 : $(OBJS_8_2_6)
	$(CC) $(LFLAGS) $(OBJS_8_2_6) -o test_8_2_6

test_8_2_7 : $(OBJS_8_2_7)
	$(CC) $(LFLAGS) $(OBJS_8_2_7) -o test_8_2_7

test_8_2_8 : $(OBJS_8_2_8)
	$(CC) $(LFLAGS) $(OBJS_8_2_8) -o test_8_2_8

test_8_2_9 : $(OBJS_8_2_9)
	$(CC) $(LFLAGS) $(OBJS_8_2_9) -o test_8_2_9

test_8_2_10 : $(OBJS_8_2_10)
	$(CC) $(LFLAGS) $(OBJS_8_2_10) -o test_8_2_10

test_8_2_11 : $(OBJS_8_2_11)
	$(CC) $(LFLAGS) $(OBJS_8_2_11) -o test_8_2_11

problem.8.2.1.o : problem.8.2.1.cpp
	$(CC) $(CFLAGS) problem.8.2.1.cpp

problem.8.2.2.o : problem.8.2.2.cpp
	$(CC) $(CFLAGS) problem.8.2.2.cpp

problem.8.2.3.o : problem.8.2.3.cpp
	$(CC) $(CFLAGS) problem.8.2.3.cpp

problem.8.2.4.o : problem.8.2.4.cpp
	$(CC) $(CFLAGS) problem.8.2.4.cpp

problem.8.2.5.o : problem.8.2.5.cpp
	$(CC) $(CFLAGS) problem.8.2.5.cpp

problem.8.2.6.o : problem.8.2.6.cpp
	$(CC) $(CFLAGS) problem.8.2.6.cpp

problem.8.2.7.o : problem.8.2.7.cpp
	$(CC) $(CFLAGS) problem.8.2.7.cpp

problem.8.2.8.o : problem.8.2.8.cpp
	$(CC) $(CFLAGS) problem.8.2.8.cpp

problem.8.2.9.o : problem.8.2.9.cpp
	$(CC) $(CFLAGS) problem.8.2.9.cpp

problem.8.2.10.o : problem.8.2.10.cpp
	$(CC) $(CFLAGS) problem.8.2.10.cpp

problem.8.2.11.o : problem.8.2.11.cpp
	$(CC) $(CFLAGS) problem.8.2.11.cpp

clean:
	\rm -rf *.o
